// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtgUj0HKPviDhzeKkytzb_7PFaIIS1umA',
    appId: '1:878840517533:web:2db85bfba328ba67bad574',
    messagingSenderId: '878840517533',
    projectId: 'seads-ambulance',
    authDomain: 'seads-ambulance.firebaseapp.com',
    databaseURL: 'https://seads-ambulance-default-rtdb.firebaseio.com',
    storageBucket: 'seads-ambulance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_78UOu-P99ak-mGysBHXMyCK2w-FQlMU',
    appId: '1:878840517533:android:6b42696576558e2cbad574',
    messagingSenderId: '878840517533',
    projectId: 'seads-ambulance',
    databaseURL: 'https://seads-ambulance-default-rtdb.firebaseio.com',
    storageBucket: 'seads-ambulance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSZVNoLj3cfZwuJKmNHI4HoZe9iwaWh2M',
    appId: '1:878840517533:ios:6fcd8b55632defaabad574',
    messagingSenderId: '878840517533',
    projectId: 'seads-ambulance',
    databaseURL: 'https://seads-ambulance-default-rtdb.firebaseio.com',
    storageBucket: 'seads-ambulance.firebasestorage.app',
    iosBundleId: 'com.example.seads',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSZVNoLj3cfZwuJKmNHI4HoZe9iwaWh2M',
    appId: '1:878840517533:ios:6fcd8b55632defaabad574',
    messagingSenderId: '878840517533',
    projectId: 'seads-ambulance',
    databaseURL: 'https://seads-ambulance-default-rtdb.firebaseio.com',
    storageBucket: 'seads-ambulance.firebasestorage.app',
    iosBundleId: 'com.example.seads',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtgUj0HKPviDhzeKkytzb_7PFaIIS1umA',
    appId: '1:878840517533:web:5f1ce463379c376bbad574',
    messagingSenderId: '878840517533',
    projectId: 'seads-ambulance',
    authDomain: 'seads-ambulance.firebaseapp.com',
    databaseURL: 'https://seads-ambulance-default-rtdb.firebaseio.com',
    storageBucket: 'seads-ambulance.firebasestorage.app',
  );
}
